[workspace]
resolver = "2"
members = [
    "train-ute",
    "raptor-rs", "patronage_data_processing",
]

# Compile dependencies with as release even in debug mode.
[profile.dev.package."*"]
opt-level = 3

[profile.release-with-symbols]
inherits = "release"
debug = true

