[package]
name = "train-ute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raptor-rs = { path = "../raptor-rs" }
chrono = { version = "0.4.38", default-features = false, features = ["serde"] }
gtfs-structures = { version = "0.41.2", default-features = false }
csv = { version = "1.3.0", default-features = false }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
tqdm = "0.7.0"

