[package]
name = "train-ute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raptor-rs = { path = "../raptor-rs" }
chrono = "0.4.38"
gtfs-structures = { version = "0.41.2", default-features = false }
